### ISSUE TITLE
Hello, author. I wanted to inquire about the generation process for 'spexy_data_3'

### ISSUE THREAD

**Issue by CATJianWang** [Alien9427/SAR_specific_models#7]
Hello, author. Thank you very much for providing the code; it has been a great help. 
However, I might have overlooked something, as I couldn't find any information in the code regarding 
how 'spexy_data_3' is generated. 
Therefore, I would like to inquire about the process of generating 'spexy_data_3.' Thank you!

**Comment by Alien9427** [comment]
> Hello, author. Thank you very much for providing the code; it has been a great help. However, I might have overlooked something, as I couldn't find any information in the code regarding how 'spexy_data_3' is generated. Therefore, I would like to inquire about the process of generating 'spexy_data_3.' Thank you!

@CATJianWang Hi, the updated version may be helpful: https://github.com/Alien9427/DSN

**Comment by CATJianWang** [comment]
@Alien9427 I have found it. Thank you very much！
